### ISSUE TITLE
make error again

### ISSUE THREAD

**Issue by NagatoYuki4** [DanWin/hosting#119]
[ 30%] Built target aom_dsp_common
[ 30%] Built target aom_dsp_encoder
make: *** [Makefile:130: all] Error 2

i still get the same problem at 30%....

**Comment by DanWin** [comment]
Hmm, I couldn't reproduce this issue. Which architecture are you building on?

**Comment by NagatoYuki4** [comment]
i'm using raspberry pi 32bit port of debian

**Comment by DanWin** [comment]
I see, that explains your issues. Using a 32 bit port will cause you problems. You should switch to 64 bit. The 32 bit port was only necessary for Raspberry Pi 1/0, which run an older ARM processor. Since Raspberry Pi 2, you can install debian armhf images (also 32 bit) and since Raspberry Pi 3 you should prefer arm64 images. See also this part of the readme:
`If you want to build it on a raspberry pi, please do not use the raspbian images as several things will break. Download an image for your pi model from https://raspi.debian.net/daily-images/ instead.`

**Comment by NagatoYuki4** [comment]
hmm i see thanks is there somewhere where i can install rpi/OS 64bit

**Comment by DanWin** [comment]
If you have a raspberry pi 3 or 4, you can get 64 bit images from [https://raspi.debian.net/daily-images](https://raspi.debian.net/daily-images). Note that the pi 0, 1 and 2 do not support 64 bit.
