### ISSUE TITLE
Edit /etc/fstab and add the noatime,usrjquota=aquota.user,jqfmt=vfsv1 option to the /home mountpoint and noatimeto /.

### ISSUE THREAD

**Issue by zwieblinger** [DanWin/hosting#128]
PROBLEM:
I have only one small problem with the installation and that is editing "/etc/fstab". Maybe someone can tell me where to insert the following task.

TASK:

Edit /etc/fstab and add the noatime,usrjquota=aquota.user,jqfmt=vfsv1 option to the /home mountpoint and noatimeto /. Then initialize quota:

CONTENTS OF MY FILE "/etc/fstab":

```
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# systemd generates mount units based on this file, see systemd.mount(5).
# Please run 'systemctl daemon-reload' after making changes here.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda1 during installation
UUID=6ce4028b-e979-4f8d-8fae-fe006fb23d06 /               ext4    errors=remount-ro >
# swap was on /dev/sda5 during installation
UUID=c0d84d53-ea06-4ba7-a6ed-4895cd8197c8 none            swap    sw              0 >
/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0

tmpfs /tmp tmpfs defaults,noatime 0 0
tmpfs /var/log/nginx tmpfs rw,user,noatime 0 0
proc /proc proc defaults,hidepid=2 0 0
```

**Comment by DanWin** [comment]
Hello,

the line you want to edit is this one: `UUID=6ce4028b-e979-4f8d-8fae-fe006fb23d06 /               ext4    errors=remount-ro 0 1`
options are separated by commas, without a space between. `errors=remount-ro` will become `errors=remount-ro,noatime,usrjquota=aquota.user,jqfmt=vfsv1`.
Since you don't have a separate /home partition, it is already on the / mountpoint. Make sure to also set `HOME_MOUNT_PATH='/';` in `common.php`
