### ISSUE TITLE
Replace the default .onion domain with your domain:

### ISSUE THREAD

**Issue by d4sec** [DanWin/hosting#130]
output : 
cat: /var/lib/tor/hidden_service/hostname: No such file or directory
sed: can't read /etc/postfix/sql/alias.cf: No such file or directory
sed: can't read /etc/postfix/sender_login_maps: No such file or directory
sed: can't read /var/www/skel/www/index.hosting.html: No such file or directory
sed: can't read /var/www/common.php: No such file or directory
sed: can't read /etc/postfix/canonical: No such file or directory
sed: can't read /etc/postfix-clearnet/canonical: No such file or directory
sed: can't read /var/www/html/squirrelmail/config/config.php: No such file or directory

**Comment by DanWin** [comment]
Hello @d4sec , it looks like you missed one step in the Readme:
`Copy (and modify according to your needs) the site files in var/www to /var/www, usr/local to /usr/local and the configuration files in etc to /etc after installation has finished. Then restart some services:`
Those files are missing, because you didn't copy them. Once you copied the files and, restart the servces, repeat this step and it should work.
