### ISSUE TITLE
How do I properly configure pseudo-static sites?

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#87]
I tried to change the nginx configuration and common.php But it doesn't seem to be working

**Comment by DanWin** [comment]
What exactly is your use case? If you need to modify the configuration of a given site, my way of dealing with it was so far to copy the `server` secion in `/etc/nginx/sites-enabled/hosted_sites` into a new file and modify the settings there. Then disable the domain in the hosting (admin) dashboard to avoid duplicate configuration. However, care must be taken, when the user account gets deleted. It will cause nginx refusing to reload the configuration due to the missing webroot, unless the customized config is removed.
The best option would of course be to have more broad customization options directly in the hosting interface, but we are not there yet.
